openapi: 3.0.0
components:
  schemas:
    GetProductsResponse:
      type: array
      items:
        $ref: '#/components/schemas/GetProductResponse'
    GetProductResponse:
      properties:
        count:
          type: integer
        description:
          type: string
        id:
          type: string
        price:
          type: integer
        title:
          type: string
info:
  title: Product Service
  version: '1'
paths:
  /products:
    get:
      summary: Get products list
      description: Get list of all products
      responses:
        200:
          description: ProductModel[]
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProductsResponse'
  /products/{productId}:
    get:
      summary: Get product by ID
      parameters:
        - name: 'productId'
          in: 'path'
          description: 'The ID of the product'
          required: true
          schema:
            type: 'string'
      responses:
        200:
          description: ProductModel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProductResponse'
